holani: enable only for x86_64
the core builds only for x86_64 targets. looks like the build picks up
header file from the host:

       Compiling libretro-rs-ffi v0.1.0 (https://github.com/libretro-rs/libretro-rs.git?rev=c7f414d19d837921b8762656e53e7f1b8f892179#c7f414d1)
    error: failed to run custom build command for `libretro-rs-ffi v0.1.0 (https://github.com/libretro-rs/libretro-rs.git?rev=c7f414d19d837921b8762656e53e7f1b8f892179#c7f414d1)`

    Caused by:
      process didn't exit successfully: `[...]/build.Lakka-AMLGX.aarch64/build/holani-0.9.6/.aarch64-libreelec-linux-gnu/target/release/build/libretro-rs-ffi-8c6a434ec6227cf4/build-script-build` (exit status: 101)
      --- stdout
      cargo:rerun-if-changed=include/libretro.h

      --- stderr
      /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
      thread 'main' panicked at [...]/build.Lakka-AMLGX.aarch64/build/rust-1.84.0/cargo_home/git/checkouts/libretro-rs-a4ab5b59ed8bbdf7/c7f414d/libretro-rs-ffi/build.rs:20:6:
      Unable to generate bindings: ClangDiagnostic("/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found\n")
                                                    ~~~~~~~~~~~~~~~~~~~~~ <- header included from the host, not the buildsystem
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace